// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.19.4
// source: ping/v1/ping.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPingPing = "/api.ping.v1.Ping/Ping"

type PingHTTPServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

func RegisterPingHTTPServer(s *http.Server, srv PingHTTPServer) {
	r := s.Route("/")
	r.GET("/ping", _Ping_Ping0_HTTP_Handler(srv))
}

func _Ping_Ping0_HTTP_Handler(srv PingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PingRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPingPing)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Ping(ctx, req.(*PingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PingResponse)
		return ctx.Result(200, reply)
	}
}

type PingHTTPClient interface {
	Ping(ctx context.Context, req *PingRequest, opts ...http.CallOption) (rsp *PingResponse, err error)
}

type PingHTTPClientImpl struct {
	cc *http.Client
}

func NewPingHTTPClient(client *http.Client) PingHTTPClient {
	return &PingHTTPClientImpl{client}
}

func (c *PingHTTPClientImpl) Ping(ctx context.Context, in *PingRequest, opts ...http.CallOption) (*PingResponse, error) {
	var out PingResponse
	pattern := "/ping"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPingPing))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
