// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos-layout/internal/conf"
	"github.com/go-kratos/kratos-layout/internal/server"
	"github.com/go-kratos/kratos-layout/internal/service"
	"github.com/go-kratos/kratos/v2"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap) (*kratos.App, func(), error) {
	confServer := bootstrap.Server
	trace := bootstrap.Trace
	tracerProvider := GetTrace(trace)
	log := bootstrap.Log
	logger := GetLogger(log)
	grpcServer := server.NewGRPCServer(confServer, tracerProvider, logger)
	graphqlService := service.NewGraphqlService(logger)
	root := service.NewRoot(logger)
	engine := server.GetGinEngine(confServer, graphqlService, root, tracerProvider, logger)
	httpServer := server.NewHTTPServer(confServer, engine, logger)
	registrar := bootstrap.Registrar
	client := GetETCD(registrar)
	registry := GetETCDRegistrar(client)
	env := bootstrap.Env
	v := GetEnv(env, logger)
	app := newApp(grpcServer, httpServer, registry, v...)
	return app, func() {
	}, nil
}
